version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    privileged: true
    devices:
      - "${DEVICE_PORT}:${DEVICE_PORT}"
    cap_add:
      - SYS_ADMIN
